### ISSUE TITLE
README.md needs adjusting for proper install

### ISSUE THREAD

**Issue by phatjmo** [adhearsion/SIPtreadmill#43]
I'm building this project for my team and came across the following error in the install instructions:

`echo "deb https://deb.packager.io/gh/adhearsion/SIPtreadmill trusty master" | sudo tee /etc/apt/sources.list.d/SIPtreadmill.list`

There is no "master" in that release, only "develop" and "feature/adhearsion-foundation".

I'm using develop, and the install works fine in docker-compose. If I should be using feature/adhearsion-foundation, please let me know.

**Comment by benlangfeld** [comment]
You should be using the master (tagged, released) versions which are provided via https://packager.io/gh/adhearsion/SIPtreadmill#master. What makes you say they don't exist?

**Comment by phatjmo** [comment]
This does: 

`Failed to fetch https://deb.packager.io/gh/adhearsion/SIPtreadmill/dists/trusty/Release  Unable to find expected entry 'master/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)`

Oh wait. The release list was suddenly updated today after I filed the issue. You must have fixed it. Thanks. I'll start using master now that it exists.

**Comment by benlangfeld** [comment]
I guess it was some problem with releases prior to the move from mojolingo/sip_treadmill to this namespace that didn't get copied across properly. Glad it's working now :)
